apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    email: devops@gmail.com
    privateKeySecretRef:
      name: acme-clusterissuer
    solvers:
    - http01:
        ingress:
          class: nginx
      selector:
        matchLabels:
          "use-http01-solver": "true"
